.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. phtevencoin_qt test_phtevencoin_qt
clean: FORCE
	$(MAKE) -C .. phtevencoin_qt_clean test_phtevencoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_phtevencoin_qt_check
phtevencoin-qt phtevencoin-qt.exe: FORCE
	 $(MAKE) -C .. phtevencoin_qt
